spring.application.name=demo
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/tech
spring.datasource.username=postgres
spring.datasource.password=12345
jwt.secret=5n42dCWXjqfiZFE5kv0ONoDyDjx/fJzufZ62nC+fdGy0May7hiokSed9GSY3bKxg
